Repository Boongeo/half-time-frontend, pull requests merged in 2024-12, with the labels that each got.

#30 refactor: 멘토 탐색 페이지의 구조 개선 및 데이터 처리 로직 리팩토링
  src/app/(main)/explore/page.tsx
  src/app/mentor/[id]/page.tsx
  src/components/explore/MentorExplore.tsx
  src/components/explore/MentorExploreServer.tsx
  src/lib/api/mentor.ts
  src/lib/hooks/useMentor.ts
  src/lib/hooks/useMentorFilter.ts
  src/lib/hooks/useMentorSearch.ts
  src/lib/services/mentorService.ts
  src/types/components/featureProps.ts
  src/types/shared/params.ts
Labels: Refactor

#31 refactor: 멘토 목록 SSR 적용
  src/app/(main)/explore/page.tsx
  src/components/explore/MentorExplore.tsx
  src/lib/hooks/useMentor.ts
  src/lib/services/mentorService.ts
  src/types/core/mentor.ts
Labels: Refactor

#32 fix: 멘토 목록 무한 스크롤 에러 수정
  src/components/common/IntersectionObserver.tsx
  src/components/explore/MentorExplore.tsx
  src/lib/hooks/useMentor.ts
  src/lib/mocks/mentors.ts
  src/lib/services/mentorService.ts
  src/types/components/commonProps.ts
Labels: BugFix

#33 feat: 멘토 상세 페이지 Calendar UI 구현
  package-lock.json
  package.json
  src/app/globals.css
  src/app/mentor/[id]/page.tsx
  src/components/common/Calendar.tsx
  src/components/mentor/MentorDetailClient.tsx
  src/components/review/ReviewCard.tsx
  src/lib/mocks/bookings.ts
  src/types/booking.ts
  src/types/react-calendar.d.ts
Labels: Feature

#36 feat: 멘토 상세 페이지 Review 섹션 구현
  src/app/mentor/[id]/page.tsx
  src/components/booking/Calendar.tsx
  src/components/common/Calendar.tsx
  src/components/mentor/MentorDetailClient.tsx
  src/components/mentor/MentorInfoTab.tsx
  src/components/mentor/MentorProfile.tsx
  src/components/review/ReviewCard.tsx
  src/components/review/ReviewFilter.tsx
  src/components/review/ReviewTab.tsx
  src/config/category.ts
  src/lib/mocks/reviews.ts
  src/store/testUser.ts
  src/types/shared/category.ts
Labels: Feature, Refactor

#39 feature: Booking 컴포넌트 구현
  package-lock.json
  package.json
  src/components/booking/BookingTab.tsx
  src/components/booking/MonthlyCalendar.tsx
  src/components/mentor/MentorDetailClient.tsx
  src/components/review/ReviewCard.tsx
  src/lib/api/booking.ts
  src/lib/hooks/useBooking.ts
  src/lib/mocks/bookings.ts
  src/lib/mocks/mentorings.ts
  src/lib/services/bookingService.ts
  src/types/core/booking.ts
  src/types/core/mentoring.ts
Labels: Feature

#40 refactor: 멘토 관련 페이지 URL 변경
  src/app/mentor/dashboard/page.tsx
  src/app/mentor/layout.tsx
  src/app/mentor/registration/page.tsx
  src/app/mentoring/[id]/page.tsx
  src/app/mentoring/layout.tsx
  src/app/mentoring/page.tsx
  src/components/mentoring/MentorRegistrationForm.tsx
  src/components/mentoring/MentoringTimeSettings.tsx
  src/components/mentoring/ProgressSteps.tsx
  src/components/mentoring/RegistrationStatus.tsx
  src/components/mentoring/sections/MentoringSection.tsx
  src/components/mentoring/sections/ProfessionalSection.tsx
  src/components/mentoring/sections/VerificationSection.tsx
Labels: Refactor

#41 Feat: 멘토 승인 상태 페이지 구현
  src/app/mentor/layout.tsx
  src/app/mentor/sessions/page.tsx
  src/app/mentor/status/page.tsx
  src/components/common/Input.tsx
  src/components/layout/Sidebar.tsx
  src/components/mentoring/MentoringTimeSettings.tsx
  src/config/sidebar.ts
  src/config/status.ts
  src/types/core/mentor.ts
  src/types/core/mentoring.ts
Labels: Feature

#42 feat: 멘토 세션 관리 페이지 UI 구현
  src/app/mentor/layout.tsx
  src/app/mentor/sessions/page.tsx
  src/components/mentoring/MentoringTimeSettings.tsx
  src/components/session/ApplicationList.tsx
  src/components/session/Controls.tsx
  src/components/session/CreateSessionModal.tsx
  src/components/session/GroupApplications.tsx
  src/components/session/IndividualApplications.tsx
  src/components/session/SessionCard.tsx
  src/components/session/SessionInfo.tsx
  src/components/session/VideoRoom.tsx
  src/lib/mocks/sessions.ts
  src/lib/utils/session.ts
  src/types/components/sessionProps.ts
  src/types/core/mentoring.ts
Labels: Feature

#43 feat: 멘토링 신청 및 예약 관리 페이지 구현
  src/app/booking/calendar/page.tsx
  src/app/booking/page.tsx
  src/components/booking/BookingCard.tsx
  src/components/booking/BookingTab.tsx
  src/components/booking/Calendar.tsx
  src/components/booking/MonthlyCalendar.tsx
  src/components/explore/MentorCard.tsx
  src/components/mentor/MentorDetailClient.tsx
  src/components/mentor/MentorInfoTab.tsx
  src/lib/api/booking.ts
  src/lib/hooks/useBooking.ts
  src/lib/hooks/useMentoring.ts
  src/lib/mocks/bookings.ts
  src/lib/mocks/mentorings.ts
  src/lib/mocks/myBookings.ts
  src/lib/services/bookingService.ts
  src/types/core/booking.ts
  src/types/core/mentoring.ts
Labels: Feature
